export const VIEW_ALL_BUSSINESS = 'VIEW_ALL_BUSSINESS';
export const VIEW_BUSSINESS = 'VIEW_BUSSINESS';
export const VIEW_BY_CATEGORIE = 'VIEW_BY_CATEGORIE';
export const LIKE_BUSSINESS = 'LIKE_BUSSINESS';