export const VIEW_ALL_COUPONS = 'VIEW_ALL_COUPONS';
export const VIEW_HOME_COUPONS = 'VIEW_HOME_COUPONS';
export const VIEW_COUPON = 'VIEW_COUPON';
export const LIKE_BUSSINESS = 'LIKE_BUSSINESS';
export const LOAD_COUPONS = 'IS_LOAD_COUPONS';
export const VIEW_COUPONS = 'CATEGORY_COUPONS';

export const BUSSINES_COUPON = 'BUSSINES_COUPON';