export const DATA_NEW_COUPON = [{
	id:"1",
	title:"Tortas al 2x1",
	short_description:"Disfruta lo mejor de nuestra rica carne bien cocida. El chile pica bien ricolino.",
	featured_image:"https://cdn2.cocinadelirante.com/sites/default/files/styles/gallerie/public/images/2018/08/torta-cubana-receta.jpg",
	initial_price:"0",
	end_price:"0",
	discount:"0",
	start_date:"0",
	end_date:"0",
	deleted:false,
	logo:"http://6am12pm.com/wp-content/uploads/2019/03/subway-logo.png",
},{
	id:"2",
	title:"Bud Light a $20",
	short_description:"Para esta calor, nada mejor que unas cervezas bien heladas. Ven y disfruta con nosotros.",
	featured_image:"https://d3f5rf6vpkkrog.cloudfront.net/images/valoraciones/0018/2000/IMG_6194_logo.JPG?1492993425",
	initial_price:"0",
	end_price:"0",
	discount:"0",
	start_date:"0",
	end_date:"0",
	deleted:false,
	logo:"https://ih0.redbubble.net/image.747182432.9753/flat,1000x1000,075,f.jpg",
},{
	id:"3",
	title:"Todo al 20% de descuento.",
	short_description:"Visitia nuestra tienda de ropa, tenemos la rebaja del año. Ven y comprueba.",
	featured_image:"https://luberalba.com/wp-content/uploads/2019/01/Marcas_de_ropa_de_hombre.jpg",
	initial_price:"0",
	end_price:"0",
	discount:"0",
	start_date:"0",
	end_date:"0",
	deleted:false,
	logo:"https://s3-ap-southeast-1.amazonaws.com/s3.loopme.ph/img/newos/brands/2x/pull-bear.png",
},{
	id:"4",
	title:"¡Arma tu hamburguesa!",
	short_description:"Ven y elige todo lo que quieras ponerle a tu hamburguesa. El precio es unico y nada caro.",
	featured_image:"https://279340-865961-raikfcquaxqncofqfm.stackpathdns.com/wp-content/uploads/2018/01/receta-hamburguesa-americana.jpeg",
	initial_price:"0",
	end_price:"0",
	discount:"0",
	start_date:"0",
	end_date:"0",
	deleted:false,
	logo:"https://www.vectorizados.com/muestras/nintendo.jpg",
},{
	id:"5",
	title:"¡Gran concierto!",
	short_description:"Ven y pasa un momento divertido con toda tu familia. ¡Completamente gratis!",
	featured_image:"https://www.diariodemexico.com/sites/default/files/field/image/concierto%20%281%29.jpg",
	initial_price:"0",
	end_price:"0",
	discount:"0",
	start_date:"0",
	end_date:"0",
	deleted:false,
	logo:"https://image.shutterstock.com/image-vector/vector-logo-karaoke-260nw-575474653.jpg",
},{
	id:"6",
	title:"Llevate tu despensa por $200",
	short_description:"¡Por única ocasión en todo el año, traemos este excelente paquete!",
	featured_image:"http://movilmaxx.com.mx/wp-content/uploads/2016/02/Screen-Shot-2016-02-08-at-6.29.39-PM-1024x680.png",
	initial_price:"0",
	end_price:"0",
	discount:"0",
	start_date:"0",
	end_date:"0",
	deleted:false,
	logo:"http://cdn2.dineroenimagen.com/media/dinero/styles/xlarge/public/images/2019/05/que-significa-logo-del-oxxo.jpg",
}];
