export const ADD_MY_FAVORITES = 'ADD_MY_FAVORITES';
export const SUPR_MY_FAVORITES = 'SUPR_MY_FAVORITES';
export const MY_TOTAL_FAVORITES = 'MY_TOTAL_FAVORITES';
export const LOAD_MY_TOTAL_FAVORITES = 'LOAD_MY_TOTAL_FAVORITES';
